import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://dolbomdoc.com";
  const paths = [
    "/",
    "/calculators/copayment",
    "/calculators/monthly-limit",
    "/calculators/reduction",
    "/calculators/salary",
    "/caregiver-info",
    "/caregiver-info/certificate",
    "/caregiver-info/exam",
    "/caregiver-info/faq",
    "/caregiver-info/jobs",
    "/caregiver-info/reality",
    "/caregiver-info/salary",
    "/community/jobs",
    "/community/questions",
    "/community/reviews",
    "/community/write",
    "/family-care-calculator",
    "/family-care-guide",
    "/family-care-guide/60min",
    "/family-care-guide/90min",
    "/family-care-guide/conditions",
    "/family-care-guide/dementia",
    "/family-care-guide/reviews",
    "/family-care-guide/salary",
    "/long-term-care",
    "/long-term-care/apply",
    "/long-term-care/benefits",
    "/long-term-care/copayment",
    "/long-term-care/faq",
    "/long-term-care/grade",
    "/regions/busan",
    "/regions/daegu",
    "/regions/incheon",
    "/regions/seoul",
    "/resources/documents",
    "/resources/forms",
    "/resources/templates",
    "/social-worker-info",
    "/social-worker-info/certificate",
    "/social-worker-info/faq",
    "/social-worker-info/jobs",
    "/social-worker-info/salary",
    "/support-benefits",
    "/support-benefits/copayment-reduction",
    "/support-benefits/documents",
    "/support-benefits/faq",
    "/support-benefits/local-support",
    "/visit-care-calculator",
    "/visit-care-guide",
    "/visit-care-guide/copayment",
    "/visit-care-guide/cost",
    "/visit-care-guide/faq",
    "/visit-care-guide/monthly-limit",
    "/visit-care-guide/service-time",
  ];

  return paths.map((p) => ({ url: `${base}${p}`, lastModified: new Date() }));
}